import Flags from 'country-flag-icons/react/3x2';
import React from 'react';

export const countryMap: Record<string, React.ComponentType<any>> = {
    "Afghanistan": Flags.AF,
    "Aland Islands": Flags.AX,
    "Albania": Flags.AL,
    "Algeria": Flags.DZ,
    "American Samoa": Flags.AS,
    "Andorra": Flags.AD,
    "Angola": Flags.AO,
    "Anguilla": Flags.AI,
    "Antarctica": Flags.AQ,
    "Antigua And Barbuda": Flags.AG,
    "Antigua and Barbuda": Flags.AG,
    "Argentina": Flags.AR,
    "Armenia": Flags.AM,
    "Aruba": Flags.AW,
    "Australia": Flags.AU,
    "Austria": Flags.AT,
    "Azerbaijan": Flags.AZ,
    "Bahamas": Flags.BS,
    "Bahrain": Flags.BH,
    "Bangladesh": Flags.BD,
    "Barbados": Flags.BB,
    "Belarus": Flags.BY,
    "Belgium": Flags.BE,
    "Belize": Flags.BZ,
    "Benin": Flags.BJ,
    "Bermuda": Flags.BM,
    "Bhutan": Flags.BT,
    "Bolivia": Flags.BO,
    "Bosnia And Herzegovina": Flags.BA,
    "Botswana": Flags.BW,
    "Bouvet Island": Flags.BV,
    "Brazil": Flags.BR,
    "British Indian Ocean Territory": Flags.IO,
    "Brunei Darussalam": Flags.BN,
    "Bulgaria": Flags.BG,
    "Burkina Faso": Flags.BF,
    "Burundi": Flags.BI,
    "Cambodia": Flags.KH,
    "Cameroon": Flags.CM,
    "Canada": Flags.CA,
    "Cape Verde": Flags.CV,
    "Cayman Islands": Flags.KY,
    "Central African Republic": Flags.CF,
    "Chad": Flags.TD,
    "Chile": Flags.CL,
    "China": Flags.CN,
    "Christmas Island": Flags.CX,
    "Cocos (Keeling) Islands": Flags.CC,
    "Colombia": Flags.CO,
    "Comoros": Flags.KM,
    "Congo": Flags.CG,
    "Congo, Democratic Republic": Flags.CD,
    "Cook Islands": Flags.CK,
    "Costa Rica": Flags.CR,
    "Cote D'Ivoire": Flags.CI,
    "Croatia": Flags.HR,
    "Cuba": Flags.CU,
    "Cyprus": Flags.CY,
    "Czech Republic": Flags.CZ,
    "Denmark": Flags.DK,
    "Djibouti": Flags.DJ,
    "Dominica": Flags.DM,
    "Dominican Republic": Flags.DO,
    "Ecuador": Flags.EC,
    "Egypt": Flags.EG,
    "El Salvador": Flags.SV,
    "Equatorial Guinea": Flags.GQ,
    "Eritrea": Flags.ER,
    "Estonia": Flags.EE,
    "Ethiopia": Flags.ET,
    "Falkland Islands (Malvinas)": Flags.FK,
    "Faroe Islands": Flags.FO,
    "Fiji": Flags.FJ,
    "Finland": Flags.FI,
    "France": Flags.FR,
    "French Guiana": Flags.GF,
    "French Polynesia": Flags.PF,
    "French Southern Territories": Flags.TF,
    "Gabon": Flags.GA,
    "Gambia": Flags.GM,
    "Georgia": Flags.GE,
    "Germany": Flags.DE,
    "Ghana": Flags.GH,
    "Gibraltar": Flags.GI,
    "Greece": Flags.GR,
    "Greenland": Flags.GL,
    "Grenada": Flags.GD,
    "Guadeloupe": Flags.GP,
    "Guam": Flags.GU,
    "Guatemala": Flags.GT,
    "Guernsey": Flags.GG,
    "Guinea": Flags.GN,
    "Guinea-Bissau": Flags.GW,
    "Guyana": Flags.GY,
    "Haiti": Flags.HT,
    "Heard Island & Mcdonald Islands": Flags.HM,
    "Holy See (Vatican City State)": Flags.VA,
    "Honduras": Flags.HN,
    "Hong Kong": Flags.HK,
    "Hungary": Flags.HU,
    "Iceland": Flags.IS,
    "India": Flags.IN,
    "Indonesia": Flags.ID,
    "Iran, Islamic Republic Of": Flags.IR,
    "Iraq": Flags.IQ,
    "Ireland": Flags.IE,
    "Isle Of Man": Flags.IM,
    "Israel": Flags.IL,
    "Italy": Flags.IT,
    "Jamaica": Flags.JM,
    "Japan": Flags.JP,
    "Jersey": Flags.JE,
    "Jordan": Flags.JO,
    "Kazakhstan": Flags.KZ,
    "Kenya": Flags.KE,
    "Kiribati": Flags.KI,
    "Korea": Flags.KR,
    "Kuwait": Flags.KW,
    "Kyrgyzstan": Flags.KG,
    "Lao People's Democratic Republic": Flags.LA,
    "Latvia": Flags.LV,
    "Lebanon": Flags.LB,
    "Lesotho": Flags.LS,
    "Liberia": Flags.LR,
    "Libyan Arab Jamahiriya": Flags.LY,
    "Liechtenstein": Flags.LI,
    "Lithuania": Flags.LT,
    "Luxembourg": Flags.LU,
    "Macao": Flags.MO,
    "Macedonia": Flags.MK,
    "Madagascar": Flags.MG,
    "Malawi": Flags.MW,
    "Malaysia": Flags.MY,
    "Maldives": Flags.MV,
    "Mali": Flags.ML,
    "Malta": Flags.MT,
    "Marshall Islands": Flags.MH,
    "Martinique": Flags.MQ,
    "Mauritania": Flags.MR,
    "Mauritius": Flags.MU,
    "Mayotte": Flags.YT,
    "Mexico": Flags.MX,
    "Micronesia, Federated States Of": Flags.FM,
    "Moldova": Flags.MD,
    "Monaco": Flags.MC,
    "Mongolia": Flags.MN,
    "Montenegro": Flags.ME,
    "Montserrat": Flags.MS,
    "Morocco": Flags.MA,
    "Mozambique": Flags.MZ,
    "Myanmar": Flags.MM,
    "Namibia": Flags.NA,
    "Nauru": Flags.NR,
    "Nepal": Flags.NP,
    "Netherlands": Flags.NL,
    "New Caledonia": Flags.NC,
    "New Zealand": Flags.NZ,
    "Nicaragua": Flags.NI,
    "Niger": Flags.NE,
    "Nigeria": Flags.NG,
    "Niue": Flags.NU,
    "Norfolk Island": Flags.NF,
    "Northern Mariana Islands": Flags.MP,
    "Norway": Flags.NO,
    "Oman": Flags.OM,
    "Pakistan": Flags.PK,
    "Palau": Flags.PW,
    "Palestinian Territory, Occupied": Flags.PS,
    "Panama": Flags.PA,
    "Papua New Guinea": Flags.PG,
    "Paraguay": Flags.PY,
    "Peru": Flags.PE,
    "Philippines": Flags.PH,
    "Pitcairn": Flags.PN,
    "Poland": Flags.PL,
    "Portugal": Flags.PT,
    "Puerto Rico": Flags.PR,
    "Qatar": Flags.QA,
    "Reunion": Flags.RE,
    "Romania": Flags.RO,
    "Russian Federation": Flags.RU,
    "Russia": Flags.RU,
    "Rwanda": Flags.RW,
    "Saint Barthelemy": Flags.BL,
    "Saint Helena": Flags.SH,
    "St. Helena": Flags.SH,
    "Saint Kitts And Nevis": Flags.KN,
    "Saint Lucia": Flags.LC,
    "Saint Martin": Flags.MF,
    "Saint Pierre And Miquelon": Flags.PM,
    "Saint Vincent And Grenadines": Flags.VC,
    "Samoa": Flags.WS,
    "San Marino": Flags.SM,
    "Sao Tome And Principe": Flags.ST,
    "Saudi Arabia": Flags.SA,
    "Senegal": Flags.SN,
    "Serbia": Flags.RS,
    "Seychelles": Flags.SC,
    "Sierra Leone": Flags.SL,
    "Singapore": Flags.SG,
    "Slovakia": Flags.SK,
    "Slovak Republic": Flags.SK,
    "Slovenia": Flags.SI,
    "Solomon Islands": Flags.SB,
    "Somalia": Flags.SO,
    "South Africa": Flags.ZA,
    "South Georgia And Sandwich Isl.": Flags.GS,
    "Spain": Flags.ES,
    "Sri Lanka": Flags.LK,
    "Sudan": Flags.SD,
    "Suriname": Flags.SR,
    "Svalbard And Jan Mayen": Flags.SJ,
    "Swaziland": Flags.SZ,
    "Sweden": Flags.SE,
    "Switzerland": Flags.CH,
    "Syrian Arab Republic": Flags.SY,
    "Taiwan": Flags.TW,
    "Tajikistan": Flags.TJ,
    "Tanzania": Flags.TZ,
    "Thailand": Flags.TH,
    "Timor-Leste": Flags.TL,
    "Togo": Flags.TG,
    "Tokelau": Flags.TK,
    "Tonga": Flags.TO,
    "Trinidad And Tobago": Flags.TT,
    "Tunisia": Flags.TN,
    "Turkey": Flags.TR,
    "Turkmenistan": Flags.TM,
    "Turks And Caicos Islands": Flags.TC,
    "Turks and Caicos Islands": Flags.TC,
    "Tuvalu": Flags.TV,
    "Uganda": Flags.UG,
    "Ukraine": Flags.UA,
    "United Arab Emirates": Flags.AE,
    "United Kingdom": Flags.GB,
    "United States": Flags.US,
    "United States Outlying Islands": Flags.UM,
    "Uruguay": Flags.UY,
    "Uzbekistan": Flags.UZ,
    "Vanuatu": Flags.VU,
    "Venezuela": Flags.VE,
    "Viet Nam": Flags.VN,
    "Virgin Islands, British": Flags.VG,
    "Virgin Islands, U.S.": Flags.VI,
    "Wallis And Futuna": Flags.WF,
    "Western Sahara": Flags.EH,
    "Yemen": Flags.YE,
    "Zambia": Flags.ZM,
    "Zimbabwe": Flags.ZW
};

export default countryMap;
